name: Build snapshot version and upload to Gradle Central

permissions: {}

on:
  push:
    branches: [main]

jobs:
  call-snapshot-job:
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-snapshot.yml@b31335d128fec7e29305eeea0b5dc7221829e1a4 # main
    with:
      project_name: "project-ncl/gradle-manipulator"
      java_version: "17"
      snapshot_deploy_args: "--info build publishToCentral -x test -x funcTest"
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
