name: Build snapshot version and upload to Gradle Central

permissions: {}

on:
  push:
    branches: [main]

jobs:
  call-snapshot-job:
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-snapshot.yml@e6fb4adb3ef1a2053b060b3dff8e4e21724f51ec # main
    with:
      project_name: "project-ncl/gradle-manipulator"
      java_version: "17"
      snapshot_deploy_args: "--info build publishToCentral -x test -x funcTest"
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
