name: Java CI with Gradle

on:
  pull_request:
    branches: [main]
    paths-ignore: ["CONTRIBUTING.md", "LICENSE", "README.md"]

permissions:
  contents: read

jobs:
  check-java-formatting:
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-ci.yml@70502d0c707f7d7abb41b02af80fb094a022a760 # main
    with:
      java_version: "17"
      gradle_version: "8.3"
      build_args: "--no-daemon --stacktrace spotlessJavaCheck"

  build-gradle-1:
    needs: [check-java-formatting]
    strategy:
      fail-fast: false
      matrix:
        gradle: [4.10.3]
    if: github.repository == 'project-ncl/gradle-manipulator'
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-ci.yml@70502d0c707f7d7abb41b02af80fb094a022a760 # main
    with:
      java_version: "11"
      gradle_version: ${{ matrix.gradle }}
      build_args: "--no-daemon --stacktrace clean build AggregateJacocoReport"
      pre_build_script: "./gradle/fix-build.sh ${{ matrix.gradle }}"
      upload_coverage: true
      coverage_files: "./build/reports/jacoco/aggregate/jacocoTestReport.xml"

  build-gradle-2:
    needs: [check-java-formatting]
    strategy:
      fail-fast: false
      matrix:
        gradle: ["9.2.1"]
        upload_artifacts: [false]
        include:
          - gradle: 9.3.0
            upload_artifacts: true
    if: github.repository == 'project-ncl/gradle-manipulator'
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-ci.yml@70502d0c707f7d7abb41b02af80fb094a022a760 # main
    with:
      fetch_all_commits: true
      java_version: "17"
      gradle_version: ${{ matrix.gradle }}
      build_args: "--no-daemon --stacktrace clean build AggregateJacocoReport"
      upload_coverage: true
      coverage_files: "./build/reports/jacoco/aggregate/jacocoTestReport.xml"
      upload_artifacts: ${{ matrix.upload_artifacts }}
