name: Build snapshot version and upload to Gradle Central

permissions: {}

on:
  push:
    branches: [main]

jobs:
  call-snapshot-job:
    uses: project-ncl/shared-github-actions/.github/workflows/gradle-snapshot.yml@646d9b629925d6405fb06ed1476aefd6b2cdca86 # v0.0.23
    with:
      project_name: "project-ncl/gradle-manipulator"
      java_version: "17"
      snapshot_deploy_args: "--info build publishToCentral -x test -x funcTest"
    secrets:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
