name: Validate GitHub Actions Workflows for this shared actions repo
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@c32f5377788ce8ee9dd823babd583c2dd18604da # v0.0.20

