name: Validate GitHub Actions Workflows for this shared actions repo
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@813d47acc2d2a4db567368b3c5335402bf1bb987 # main

